name: build-install-image
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - '**.md'
  schedule:
    - cron: '20 20 * * *'  # 8:20pm everyday
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'

jobs:
  create-installer:
    name: Build and push image
    runs-on: ubuntu-22.04
    permissions:
      contents: read

    steps:
      - name: Install mkisofs
        run: sudo apt update && sudo apt install mkisofs

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - run: lsblk

      - name: Select drive
        run: |
          DRIVES=$(lsblk | grep 14G)
          DRIVE=$(echo $DRIVES | cut -d " " -f 1)
          echo $DRIVES
          echo $DRIVE
          
          echo "DRIVE=$DRIVE" >> $GITHUB_ENV

      #- name: Create virtual disk ±5gb
      #  run: sudo dd if=/dev/zero of=/media/VHD.img bs=1M count=5000 && sudo mkfs -t ext4 /media/VHD.img

      - name: try to install fedora to the virtual disk
        run: sudo docker run --privileged --pid=host --net=none --security-opt label=type:unconfined_t ghcr.io/cgwalters/fedora-oscore bootc install --target-no-signature-verification /dev/${{ env.DRIVE }}

      #- name: Mount virtual disk
      #  run: sudo mkdir /mnt/VHD/ && sudo mount -t auto -o loop /media/VHD.img /mnt/VHD/

      - name: Create ISO file
        #run: sudo mkisofs -o /media/iso.iso /mnt/VHD/
        run: sudo mkisofs -o /media/iso.iso /dev/${{ env.DRIVE }}

      - name: Upload ISO file
        uses: actions/upload-artifact@v3
        with:
          name: x86_64-i-think
          path: /media/iso.iso